// flow-typed signature: fd65e57f97fdea102a7e0a29ed14f04a
// flow-typed version: <<STUB>>/gulp-clean-css_v^3.0.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-clean-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-clean-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-clean-css/index' {
  declare module.exports: $Exports<'gulp-clean-css'>;
}
declare module 'gulp-clean-css/index.js' {
  declare module.exports: $Exports<'gulp-clean-css'>;
}
