export const PLAYER_READY  = 'PLAYER_READY'
export const PLAYER_PLAY   = 'PLAYER_PLAY'
export const PLAYER_PAUSE  = 'PLAYER_PAUSE'
export const PLAYER_STOP   = 'PLAYER_STOP'
export const PLAYER_SEEK   = 'PLAYER_SEEK'
export const PLAYER_LOAD   = 'PLAYER_LOAD'
export const PLAYER_VOLUME = 'PLAYER_VOLUME'